name: drive
description: "Drive to shop application for Serchservice Inc."

publish_to: 'none'

version: 1.0.3+17

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.4
  flutter_svg:
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.10
  firebase_core: ^3.9.0
  firebase_remote_config: ^5.2.0
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6
  firebase_messaging: ^15.1.6
  awesome_notifications: ^0.10.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.8.0
  auto_size_text: ^3.0.0
  webview_flutter: ^4.10.0
  webview_flutter_android: any
  webview_flutter_wkwebview: any
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  app_links: ^6.3.3
  device_info_plus: ^11.2.0
  device_safety_info: ^0.0.9
  package_info_plus: ^8.1.2
  toastification: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.10
  in_app_update: ^4.2.3
  map_launcher: ^3.5.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  google_directions_api: ^0.10.0
  google_mobile_ads: ^2.4.0
  onesignal_flutter: ^5.2.9
  infinite_scroll_pagination: ^4.1.0

  connectify_flutter:
    git:
      url: https://github.com/Serchservice/connectify_flutter.git
      ref: main

  logger_flutter:
    git:
      url: https://github.com/Serchservice/logger_flutter.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^2.0.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/logo/
    - asset/common/
    - asset/theme/
    - asset/map/
    - asset/app/
    - .env

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "asset/logo/app-icon.png"
  adaptive_background_color: "#4361EE"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "asset/logo/app-icon.png"
    background_color: "#4361EE"
    theme_color: "#4361EE"
  windows:
    generate: true
    image_path: "asset/logo/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "asset/logo/app-icon.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#4361EE"
  # background_image: "asset/lightWallpaper.png"
  image: asset/logo/splash-screen.png
  branding: asset/logo/branding-android.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom
  # color_dark: "#030001"
  # background_image_dark: asset/darkWallpaper.png
  # image_dark: asset/logo/splashWhite.png
  # branding_dark: asset/logo/tagWhite.png
  android_12:
    image: asset/logo/splash-screen-android-12.png
    color: "#4361EE"
    # icon_background_color: "#030001"
    branding: asset/logo/branding-android-12.png
    # image_dark: asset/logo/splashWhite.png
    # color_dark: "#030001"
    # icon_background_color_dark: "#FFFFFF"
    # branding_dark: asset/logo/tagWhite.png
  #android: false
  #ios: false
  #web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  #android_screen_orientation: sensorLandscape
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
