// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_configuration.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseConfiguration {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYgOst0EBqRskuU7hJt8Lw3OqXFwS2dI',
    appId: '1:977124095958:web:996ef3bf6aaea2b15a9677',
    messagingSenderId: '977124095958',
    projectId: 'serch-drive',
    authDomain: 'serch-drive.firebaseapp.com',
    storageBucket: 'serch-drive.firebasestorage.app',
    measurementId: 'G-8LDPB11Y20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpixbFdRc_Z3XR3wwbWMlAy_TbaWYXCBg',
    appId: '1:977124095958:android:f02307e58c5886e15a9677',
    messagingSenderId: '977124095958',
    projectId: 'serch-drive',
    storageBucket: 'serch-drive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6ptQwN2NE2qaObC2Z6TO1AIqA-ZYaN0',
    appId: '1:977124095958:ios:85dff033559a2d415a9677',
    messagingSenderId: '977124095958',
    projectId: 'serch-drive',
    storageBucket: 'serch-drive.firebasestorage.app',
    iosBundleId: 'com.serchservice.drive',
  );
}
