name: Release and Publish Static Web

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.activity_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Get version and build number from version.json
        id: get_version_and_build
        run: |
          VERSION=$(jq -r .version web/version.json)
          BUILD_NUMBER=$(jq -r .build_number web/version.json)
          VERSION_WITH_BUILD="web-v${VERSION}+${BUILD_NUMBER}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "VERSION_WITH_BUILD=$VERSION_WITH_BUILD" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag "v${{ env.VERSION_WITH_BUILD }}"
          git push origin "v${{ env.VERSION_WITH_BUILD }}"
          echo "Tag created: v${{ env.VERSION_WITH_BUILD }}"

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION_WITH_BUILD }}" \
            --title "Release v${{ env.VERSION_WITH_BUILD }}" \
            --notes "Release notes for version v${{ env.VERSION }}+${{ env.BUILD_NUMBER }}"